### PR TITLE
Design revamp July 2022

### PR DESCRIPTION
**Pull request by rajanwastaken**
This PR includes the initial commit for the Club Application page's revamp in July 2022.

Updates to the Site:
- A new timeline at the top to guide applicants through the process (with live progress updates)
- Confetti and surprises throughout the application process to make it more personal
- Rethought questions/labels to make the process more inclusive
- Application tracker to share an estimated time of when to expect response
- On-submit welcome email to share progress
- New UX for home page and review page for simplicity in flow (ie. inline alerts, new landing page, live updates on status)

What remains to be fixed before merging to production (almost done!):
- Full translations between English and Portuges
- Autosave bug on final fields
- On-mount rendering for club page bug
- Dropdown for phone number
- Address autocomplete

image
image

### CODE REVIEW

**Review by sampoder — COMMENTED** [review]
Wow, thank you @rajanwastaken. This PR is magical, look forward to reviewing it more in-depth!

**Comment by sampoder** [comment]
On translations, please contact @adrianoapj, thanks!

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**…ation\]/\[leader\]/\[type\]**](https://apply-pu14e10hn.hackclub.dev/[application]/[leader]/[type]) | [**/\[application\]/\[leader\]**](https://apply-pu14e10hn.hackclub.dev/[application]/[leader]) |
|:-:|:-:|
|<a href="https://apply-pu14e10hn.hackclub.dev/[application]/[leader]/[type]">Screenshot of /[application]/[leader]/[type]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/z9X3uvWlJStkQczbE7AYTbI-ugGdiP8O_CB2VPmv-5fnCbsPW_6U4oz1mNJsLYttPRHvGujfSKza5dFtV_a0ag.png">(view full size)</a> |<a href="https://apply-pu14e10hn.hackclub.dev/[application]/[leader]">Screenshot of /[application]/[leader]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/ocNLpiGE3SaNbgT3y_Ahq51D0Rixoqaq31W-CJUzxlDVhxyU2k001x_5KUgw-M70P9BPejzJLfOF5bbxe9boQw.png">(view full size)</a> |



| [**…ion\]/\[leader\]/register**](https://apply-pu14e10hn.hackclub.dev/[application]/[leader]/register) | [**…ation\]/\[leader\]/review**](https://apply-pu14e10hn.hackclub.dev/[application]/[leader]/review) |
|:-:|:-:|
|<a href="https://apply-pu14e10hn.hackclub.dev/[application]/[leader]/register">Screenshot of /[application]/[leader]/register</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/3D7eC7obUG2u5bQh7Wph6d71_OOzlxxCkU_O0mLp2B_2JmKUIBCtcsbDO8SFF4NlA55SKgYdZ8li_OgZBVveLA.png">(view full size)</a> |<a href="https://apply-pu14e10hn.hackclub.dev/[application]/[leader]/review">Screenshot of /[application]/[leader]/review</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/bEXv2ffBKpdHqDXcufBAG4x7t4lDxU0aST-sJcyclxEpUrXmqUuwgeMzS527MVvxv7GEK__ecN1gSuzZkVdXcw.png">(view full size)</a> |



| [**…ation\]/\[leader\]/status**](https://apply-pu14e10hn.hackclub.dev/[application]/[leader]/status) | [**/**](https://apply-pu14e10hn.hackclub.dev/) |
|:-:|:-:|
|<a href="https://apply-pu14e10hn.hackclub.dev/[application]/[leader]/status">Screenshot of /[application]/[leader]/status</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/YQkHI1ixXxKZbUJ4sC1hA4x_iGkxk7q5A4DsciFX-HUJ1ls1eYwKxFTcHYg_AeCbBpukX3UVrMlzF2Bo6Jkq6g.png">(view full size)</a> |<a href="https://apply-pu14e10hn.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/yJY2oDkCWX9wRlCmhlAYuqyM2PQ-2QSE3jK2J-8ibQESKMureNI9ZWBNB9BFYPtXtheCzKogl-LcBALCG348sQ.png">(view full size)</a> |







Commit f2091b96888ae72f7940654ca0267fcfc5a68c45 (https://apply-pu14e10hn.hackclub.dev).

**Comment by rajanwastaken** [comment]
@sampoder autosave/onmount bugs, revised UX flow and full translations are pushed 😄 You can review the latest version at [https://hackclub-apply.vercel.app](https://hackclub-apply.vercel.app). When you get a login email, just change `apply.hackclub.com` to `hackclub-apply.vercel.app`

**Review by sampoder — APPROVED** [review]
@rajanwastaken ran through the site and made a video of me making a club application and talking about the site design: https://youtu.be/DZ6UpBQV7mc (it's uploading, will be ready 12:24-ish)

let me know if this format is helpful, if you'd like me to write anything done, send over example code or to jump on zoom call :D

❤️ the work you've done here.

**Comment by sampoder** [comment]
Screenshot 2022-07-27 at 7 43 36 AM

Slightly reworked copy (person preferences)

Hack yeah! Your application was submitted and you're another step closer to running your Hack Club!

Now, we'll take some time to review what you worked so hard on. We'll be reaching out within 24 hours Monday - Friday (or 48 hours if it's a weekend) to let you know if you're in. Then we'll work to schedule a welcome call where you'll get to know your main contact from HQ via Zoom!

While you wait, here's some stuff to keep you entertained:

- Check out this video from our mobile hackathon in 2021: [The Hacker Zephyr](https://www.youtube.com/watch?v=2BID8_pGuqA)!
- [Join us on Slack](https://hackclub.com/slack/) if you haven't already and get some inspiration by checking out the #ship and #scrapbook channels
- Build a game using [Sprig](https://sprig.hackclub.com).... insert a description of Sprig....

We can't wait to meet you!

\- Hack Club HQ

**Comment by zachlatta** [comment]
Hey, we have a launch going out shortly, so I'm going to go ahead and merge this. @sampoder, I know things are crazy with Assemble. Can you do a code review here for @rajanwastaken after things cool down next week? Thanks so much everyone, and great work!

**Comment by sampoder** [comment]
Hey @zachlatta! Awesome, I did my best attempt of a code review on the flight a couple of hours ago, GitHub (was driving Max and I insane) wasn't working very well so I sent all feedback through Slack to Rajan.

I'll do a more comprehensive code review next week when the dust settles.

**Pull request merged**
