### PR TITLE
Change FYI functionality

### PR DESCRIPTION
**Pull request by jianmin-chen**
Instead of just alerting the user when they don't meet the age requirement to run a Hack Club (max is 20 years), they will not be allowed to fill out the forms, unless they add another leader who *does* meet the age requirements. 

Build runs fine locally.

Thought process:

1. Leader signs up.
2. Leader fills out form, meets age requirements. Awesome! They can continue.
3. Leader fills out form, they do not meet age requirements. They are only allowed to edit the birthday field and invite other leaders.
4. At least one leader meets the age requirements. Awesome! They can continue.

### CODE REVIEW

**Review by sampoder — APPROVED** [review]
Looks good! Will merge, test, and revert back in case I run into anything. Thanks @jianmin-chen!

**Comment by sampoder** [comment]
Hey @jianmin-chen! Just tested this and it looks like I was able to submit as someone born in 2000:

Screenshot 2023-01-06 at 10 22 29 PM

Screenshot 2023-01-06 at 10 25 48 PM

Seems to be a client side issue, I'm using Arc, which browser are you using to test?

**Comment by sampoder** [comment]
It doesn't seem like the previous FYI warning was working on my browser either.

**Comment by sampoder** [comment]
Same thing in Firefox:

Screenshot 2023-01-06 at 10 29 03 PM

**Comment by jianmin-chen** [comment]
Are you running locally? Personally I kept forgetting to replace the `apply.hackclub.com` link the email sent me with the appropriate port (e.g. `localhost:3000`). I'll take a look and let you know if I fix it.

**Comment by jianmin-chen** [comment]
Just read your comments more fully... hmm. I'll check when I get home.

**Comment by sampoder** [comment]
I'm running this on `apply.hackclub.com`

**Pull request merged**
