### PR TITLE
added locale switcher button

### PR DESCRIPTION
**Pull request by vitorvavolizza**
:)

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**…ation\]/\[leader\]/\[type\]**](https://apply-efqoijga3.hackclub.dev/[application]/[leader]/[type]) |
|:-:|
|<a href="https://apply-efqoijga3.hackclub.dev/[application]/[leader]/[type]">Screenshot of /[application]/[leader]/[type]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/778LI0jUbbW23ZIKE5ZKKDK5dx22Ct3wHJNK-pPYkqF1pByK6FtAl-CoPIS6jOql07nWkp1ElrV9-4hm22It3Q.png">(view full size)</a> |







Commit 472b89bf52801b33dd9fb19722992f92b83eb1b8 (https://apply-efqoijga3.hackclub.dev).

**Review by sampoder — APPROVED** [review]
This is wonderful, thank you!

A couple of things:

- On the login page, the box is no longer centered vertically
- Could we use human names for the languages (for example "English"), see the workshops site for how we're doing this
- Could you remove the formatting changes to help me review

Thanks!

**Comment by vitorvavolizza** [comment]
done @sampoder! :)

**Review by sampoder — APPROVED** [review]
Amazing!

**Pull request merged**
